### ISSUE TITLE
Is the song name database thing implemented? 

### ISSUE THREAD

**Issue by Manic137** [Hydr8gon/Project-DS#4]
Not sure if I did it right, but these are the files I put in the db folder

![image](https://user-images.githubusercontent.com/88038453/183262093-d547a7be-21b4-4aaa-84e6-3dd69aab5507.png)

**Comment by Hydr8gon** [comment]
It only needs files with "pv_db" in the name, but yes, song names and lyrics should work. It only supports English strings for now, so if it's not working that might be why.

**Comment by Manic137** [comment]
> It only needs files with "pv_db" in the name, but yes, song names and lyrics should work. It only supports English strings for now, so if it's not working that might be why.

Ahh, I see, makes sense!
